### ISSUE TITLE
ronn.xcodeproj does not exist

### ISSUE THREAD

**Issue by jmarcosfer** [csteinmetz1/ronn#3]
hey!

I was having trouble getting Reaper or Logic to detect the plugin so I tried building it, but got this error and can't figure out what's going on:

```
-> ./build.sh
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_C_COMPILER could be found.



CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_CXX_COMPILER could be found.



-- Configuring incomplete, errors occurred!
See also "/Users/jorge-work/Downloads/ronn-master/plugin/juce/ronn/build/CMakeFiles/CMakeOutput.log".
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project ronn.xcodeproj build -target ALL_BUILD -configuration Debug -hideShellScriptEnvironment

User defaults from command line:
    HideShellScriptEnvironment = YES

xcodebuild: error: 'ronn.xcodeproj' does not exist.
```

I tried changing the `-DCMAKE_PREFIX_PATH` on the juce/ronn/build.sh script to where libtorch is on my computer, but that didn't seem to help...

thanks for the work, it looks like it must be a lot of fun to play with

**Comment by csteinmetz1** [comment]
Hey @jmarcosfer, thanks for taking a look at the project!

After checking out the README I realized that some details were missing. 
You will also need to have [FRUT](https://github.com/McMartin/FRUT) installed. See their README for details. 

In addition to updating the libtorch path in `build.sh`, you will also need to edit the `CMakeLists.txt` file and update some paths in there. See the commented lines below. You will need to update the relative path to your local install of FRUT, as well as the path to your JUCE install. 

```
# This file was generated by FRUT's Jucer2CMake from "ronn.jucer"

cmake_minimum_required(VERSION 3.4)

project("ronn")

# Update the path below to reflect the correct relative path to FRUT on your system
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../../../../../FRUT/prefix/FRUT/cmake")
include(Reprojucer)

find_package(Torch REQUIRED)

set(ronn_jucer_FILE
  "${CMAKE_CURRENT_LIST_DIR}/ronn.jucer"
)

# Set the absolute path to your JUCE installation
set(JUCE_MODULES_GLOBAL_PATH "/path/to/JUCE/modules")```

I updated the steps in the README to make it slightly clearer. Let me know if this helps. I can provide further details if you run into any issues with these steps.

**Comment by jmarcosfer** [comment]
Thanks @csteinmetz1! 

I've followed your path changes, and installed FRUT, but unfortunately I'm still getting the exact same error.

I could share the CMakeOutput.log if that's of any help? 

I had at look at my cmake version (3.15.4) since I saw on the CMakeLists.txt that the minimum required is version 3.4 but I could only find the latest stable release is 3.20 🤷🏼‍♂️

Could it be something to do with my Xcode install?

**Comment by csteinmetz1** [comment]
Hey @jmarcosfer,
I know its been a while, but I have circled back around and tried to make the build process a lot simpler using CMake via the new JUCE integration. This doesn't require FRUT, which makes the paths easier. If you are still interested, I am curious if this new update works for you. I'd suggest cloning a new copy of the repo to start and follow the new instructions in the README. Let me know if you give it a try. Thanks!

**Comment by jmarcosfer** [comment]
thanks a lot Christian! will definitely give it a try as soon as I get some time, I'll let you know how it goes

**Comment by leoauri** [comment]
Hey, I just wanted to report, I had the same problem with DAWs not recognising the plugins. I was able to successfully compile locally and now Ableton sees the ronn vst3 and it runs 👍

**Comment by leoauri** [comment]
It was necessary to add

`CMAKE_PREFIX_PATH="libtorch" cmake -Bbuild -GXcode "-DCMAKE_OSX_ARCHITECTURES==i386;x86_64"`

to the build command...

**Comment by csteinmetz1** [comment]
Thanks for trying this out @leoauri! I just added a new line in the `CMakeLists.txt` that will add the `libtorch` directory to the path automatically. The current setup is working well for me now on macOS.
